spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotel
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root1
    password: root1
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update