INSERT INTO country (country_code, country_name, phone_code)
VALUES
('AFG', 'Afghanistan', '+93'),
('ALB', 'Albania', '+355'),
('DZA', 'Algeria', '+21'),
('ASM', 'American Samoa', '+684'),
('AND', 'Andorra', '+376'),
('AGO', 'Angola', '+244'),
('AIA', 'Anguilla', '+1264'),
('ATG', 'Antigua and Barbuda', '+1268'),
('ARG', 'Argentina', '+54'),
('ARM', 'Armenia', '+374'),
('ABW', 'Aruba', '+297'),
('AUS', 'Australia', '+61'),
('AUT', 'Austria', '+43'),
('AZE', 'Azerbaijan', '+994'),
('BHS', 'Bahamas', '+1242'),
('BHR', 'Bahrain', '+973'),
('BGD', 'Bangladesh', '+880'),
('BRB', 'Barbados', '+1246'),
('BLR', 'Belarus', '+375'),
('BEL', 'Belgium', '+32'),
('BLZ', 'Belize', '+501'),
('BEN', 'Benin', '+229'),
('BMU', 'Bermuda', '+1441'),
('BTN', 'Bhutan', '+975'),
('BOL', 'Bolivia', '+591'),
('BIH', 'Bosnia & Herzegovina', '+387'),
('BWA', 'Botswana', '+267'),
('BRA', 'Brazil', '+55'),
('IOT', 'British Indian Ocean Territory', '+1284'),
('BRN', 'Brunei Darussalam', '+673'),
('BGR', 'Bulgaria', '+359'),
('BFA', 'Burkina-Faso', '+226'),
('BDI', 'Burundi', '+257'),
('KHM', 'Cambodia', '+855'),
('CMR', 'Cameroon', '+237'),
('CAN', 'Canada', '+1'),
('CPV', 'Cape Verde', '+238'),
('CYM', 'Cayman Islands', '+1345'),
('CAF', 'Central African Republic', '+236'),
('TCD', 'Chad', '+235'),
('CHL', 'Chili', '+56'),
('CHN', 'China', '+86'),
('CXR', 'Christmas Island', '+672'),
('CCK', 'Cocos Islands', '+672'),
('COL', 'Colombia', '+57'),
('COM', 'Comoros Island', '+269'),
('COG', 'Congo', '+242'),
('COD', 'Congo, Democratic Republic of the', '+243'),
('COK', 'Cook Islands', '+682'),
('CRI', 'Costa Rica', '+506'),
('CIV', 'Cote dIvoire', '+225'),
('HRV', 'Croatia', '+385'),
('CUB', 'Cuba', '+53'),
('CYP', 'Cyprus', '+357'),
('CZE', 'Czech Republic', '+420'),
('DNK', 'Denmark', '+45'),
('DJI', 'Djibouti', '+253'),
('DMA', 'Dominica', '+1767'),
('DOM', 'Dominican Republic', '+1809'),
('TMP', 'East Timor', '+62'),
('ECU', 'Ecuador', '+593'),
('EGY', 'Egypt', '+20'),
('SLV', 'El Salvador', '+503'),
('GNQ', 'Equatorial Guinea', '+240'),
('ERI', 'Eritrea', '+291'),
('EST', 'Estonia', '+372'),
('ETH', 'Ethiopia', '+251'),
('FLK', 'Falkland Islands', '+500'),
('FRO', 'Faroe Islands', '+298'),
('FSM', 'Federated States of Micronesia', '+691'),
('FJI', 'Fiji', '+679'),
('FIN', 'Finland', '+358'),
('FRA', 'France', '+33'),
('GUF', 'French Guyana', '+594'),
('PYF', 'French Polynesia', '+689'),
('GAB', 'Gabon', '+241'),
('GMB', 'Gambia', '+220'),
('GEO', 'Georgia', '+995'),
('DEU', 'Germany', '+49'),
('GHA', 'Ghana', '+233'),
('GIB', 'Gibraltar', '+350'),
('GBR', 'Great Britain (United Kingdom)', '+44'),
('GRC', 'Greece', '+30'),
('GRL', 'Greenland', '+299'),
('GRD', 'Grenada', '+1473'),
('GLP', 'Guadeloupe', '+590'),
('GUM', 'Guam', '+1'),
('GTM', 'Guatemala', '+502'),
('GIN', 'Guinea', '+224'),
('GNB', 'Guinea-Bissau', '+245'),
('GUY', 'Guyana', '+592'),
('HTI', 'Haiti', '+509'),
('HND', 'Honduras', '+504'),
('HKG', 'Hong Kong', '+852'),
('HUN', 'Hungary', '+36'),
('ISL', 'Iceland', '+354'),
('IND', 'India', '+91'),
('IDN', 'Indonesia', '+62'),
('IRN', 'Iran', '+98'),
('IRQ', 'Iraq', '+964'),
('IRL', 'Ireland', '+353'),
('ISR', 'Israel', '+972'),
('ITA', 'Italy', '+39'),
('JAM', 'Jamaica', '+1876'),
('JPN', 'Japan', '+81'),
('JOR', 'Jordan', '+962'),
('KAZ', 'Kazakhstan', '+7'),
('KEN', 'Kenya', '+254'),
('KGZ', 'Kirghizstan', '+996'),
('KIR', 'Kiribati', '+686'),
('PRK', 'North Korea', '+850'),
('KOR', 'South Korea', '+82'),
('KWT', 'Kuwait', '+965'),
('LAO', 'Laos', '+856'),
('LVA', 'Latvia', '+371'),
('LBN', 'Lebanon', '+961'),
('LSO', 'Lesotho', '+266'),
('LBR', 'Liberia', '+231'),
('LBY', 'Libyan Arab Jamahiriya', '+21'),
('LIE', 'Liechtenstein', '+41'),
('LTU', 'Lithuania', '+370'),
('LUX', 'Luxembourg', '+352'),
('MAC', 'Macau (Macao)', '+853'),
('MKD', 'Macedonia', '+389'),
('MDG', 'Madagascar', '+261'),
('MWI', 'Malawi', '+265'),
('MYS', 'Malaysia', '+60'),
('MDV', 'Maldives', '+960'),
('MLI', 'Mali', '+223'),
('MLT', 'Malta', '+356'),
('MAR', 'Marocco', '+212'),
('MHL', 'Marshall Islands', '+692'),
('MTQ', 'Martinique', '+596'),
('MRT', 'Mauritania', '+222'),
('MUS', 'Mauritius', '+230'),
('MYT', 'Mayotte', '+262'),
('MEX', 'Mexico', '+52'),
('MDA', 'Moldova', '+373'),
('MCO', 'Monaco', '+377'),
('MNG', 'Mongolia', '+976'),
('MSR', 'Montserrat', '+1664'),
('MOZ', 'Mozambique', '+258'),
('MMR', 'Myanmar', '+95'),
('NAM', 'Namibia', '+264'),
('NRU', 'Nauru', '+674'),
('NPL', 'Nepal', '+977'),
('NLD', 'Netherlands (Holland)', '+31'),
('ANT', 'Netherlands Antilles', '+599'),
('NCL', 'New Caledonia', '+687'),
('NZL', 'New Zealand', '+64'),
('NIC', 'Nicaragua', '+505'),
('NER', 'Niger', '+227'),
('NGA', 'Nigeria', '+234'),
('NIU', 'Niue', '+683'),
('NFK', 'Norfolk Island', '+672'),
('MNP', 'Northern Mariana Islands', '+670'),
('NOR', 'Norway', '+47'),
('OMN', 'Oman', '+968'),
('PAK', 'Pakistan', '+92'),
('PLW', 'Palau', '+680'),
('PAN', 'Panama', '+507'),
('PNG', 'Papua New Guinea', '+675'),
('PRY', 'Paraguay', '+595'),
('PER', 'Peru', '+51'),
('PHL', 'Philippines', '+63'),
('PCN', 'Pitcairn', '+649'),
('POL', 'Poland', '+48'),
('PRT', 'Portugal', '+351'),
('PRI', 'Puerto Rico', '+1787'),
('QAT', 'Qatar', '+974'),
('REU', 'Reunion', '+262'),
('ROM', 'Romania', '+40'),
('RUS', 'Russia (Russian Federation)', '+7'),
('RWA', 'Rwanda', '+250'),
('KNA', 'Saint Kitts and Nevis', '+1869'),
('LCA', 'Saint Lucia', '+1758'),
('VCT', 'Saint Vincent and the Grenadines', '+1809'),
('WSM', 'Samoa', '+1684'),
('SMR', 'San Marino', '+39'),
('STP', 'Sao Tomea and Principe', '+239'),
('SAU', 'Saudi Arabia', '+966'),
('SEN', 'Senegal', '+221'),
('SYC', 'Seychelles', '+248'),
('SLE', 'Sierra Leone', '+232'),
('SGP', 'Singapore', '+65'),
('SVK', 'Slovakia', '+421'),
('SVN', 'Slovenia', '+386'),
('SLB', 'Solomon Islands', '+677'),
('SOM', 'Somali', '+252'),
('ZAF', 'South Africa', '+27'),
('SGS', 'South Georgia and the South Sandwich Islands', '+500'),
('ESP', 'Spain', '+34'),
('LKA', 'Sri Lanka', '+94'),
('SPM', 'St. Pierre and Miquelon', '+508'),
('SDN', 'Sudan', '+249'),
('SUR', 'Surinam', '+597'),
('SJM', 'Svalbard and Jan Mayen Islands', '+47'),
('SWZ', 'Swaziland', '+268'),
('SWE', 'Sweden', '+46'),
('CHE', 'Switzerland', '+41'),
('SYR', 'Syria', '+963'),
('TJK', 'Tadjikistan', '+992'),
('TWN', 'Taiwan', '+886'),
('TZA', 'Tanzania', '+255'),
('THA', 'Thailand', '+66'),
('TGO', 'Togo', '+228'),
('TKL', 'Tokelau', '+690'),
('TON', 'Tonga', '+676'),
('TTO', 'Trinidad and Tobago', '+1868'),
('TUN', 'Tunisia', '+21'),
('TUR', 'Turkey', '+90'),
('TKM', 'Turkmenistan', '+993'),
('TCA', 'Turks and Caicos Islands', '+1649'),
('TUV', 'Tuvalu', '+688'),
('UGA', 'Uganda', '+256'),
('UKR', 'Ukraine', '+380'),
('ARE', 'United Arab Emirates', '+971'),
('UMI', 'United States Minor Outlying Islands', '+1808'),
('USA', 'United States of America', '+1'),
('URY', 'Uruguay', '+598'),
('UZB', 'Uzbekistan', '+998'),
('VUT', 'Vanuatu', '+678'),
('VAT', 'Vatican', '+39'),
('VEN', 'Venezuela', '+58'),
('VNM', 'Vietnam', '+84'),
('VGB', 'Virgin Islands, British', '+1284'),
('VIR', 'Virgin Islands, US', '+1340'),
('WLF', 'Wallis and Futuna Islands', '+681'),
('ESH', 'Western Sahara', '+21'),
('YEM', 'Yemen', '+967'),
('YUG', 'Yugoslavia', '+381'),
('ZMB', 'Zambia', '+260'),
('ZWE', 'Zimbabwe', '+263');